[buildPlans.Ioveska]
family = "Ioveska"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

[buildPlans.Ioveska.variants.design]
two = "straight-neck-serifless"
# three = "flat-top-serifless"
# four = "closed-serifless"
eight = "two-circles"
capital-d = "more-rounded-serifless"
# capital-g = "toothless-corner-serifless-hooked"
capital-g = "toothless-rounded-serifless-hooked"
# capital-w = "straight-almost-flat-top-serifless"
u = "toothless-rounded-serifless"
# w = "straight-almost-flat-top-serifless"
# w = "straight-flat-top-serifless"
# asterisk = "penta-low"
paren = "large-contour"
dollar = "open"
cent = "open"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

[buildPlans.Ioveska.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Ioveska.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Ioveska.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.Ioveska.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.Ioveska.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Ioveska.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.Ioveska.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.Ioveska.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"